apiVersion: v1
kind: ConfigMap
metadata:
  name: quantum-nlp-config
  namespace: quantum-nlp
  labels:
    app.kubernetes.io/name: quantum-nlp-platform
    app.kubernetes.io/component: config
data:
  # Application configuration
  application.yaml: |
    server:
      port: 8080
      host: "0.0.0.0"
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 60s
      shutdown_timeout: 30s
    
    # Database configuration
    database:
      host: postgresql
      port: 5432
      name: quantum_nlp
      user: quantum_user
      ssl_mode: require
      max_open_conns: 25
      max_idle_conns: 5
      conn_max_lifetime: 1h
    
    # Redis configuration
    redis:
      host: redis
      port: 6379
      db: 0
      pool_size: 10
    
    # Neo4j configuration
    neo4j:
      uri: bolt://neo4j:7687
      database: quantum_nlp
    
    # Logging configuration
    logging:
      level: info
      format: json
    
    # Rate limiting
    rate_limit:
      requests: 1000
      window: 60s
    
    # QLAFS configuration
    qlafs:
      fingerprinting:
        enabled: true
        algorithms:
          static: ["sha256", "blake3"]
          behavioral: ["entropy", "timing"]
          cognitive: ["attention", "reasoning"]
          compositional: ["structure", "dependencies"]
      
      consensus:
        enabled: true
        algorithm: "pbft"
        validator_count: 7
        timeout: 30s
        fault_tolerance: 2
      
      transparency:
        enabled: true
        log_retention: "2y"
        anchoring:
          enabled: true
          interval: "1h"
          blockchain: "ethereum-sepolia"
      
      trust_engine:
        enabled: true
        factors:
          verification_history: 0.3
          consensus_participation: 0.2
          behavioral_consistency: 0.2
          performance_metrics: 0.2
          security_incidents: 0.1

  # Frontend configuration
  frontend.env: |
    NEXT_PUBLIC_API_URL=http://nlp-gateway:8080/api/v1
    NEXT_PUBLIC_WS_URL=ws://nlp-gateway:8080/ws
    NEXT_PUBLIC_SENTRY_DSN=
    NEXT_PUBLIC_ANALYTICS_ID=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: quantum-nlp-monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "/etc/prometheus/rules/*.yml"
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093
    
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - quantum-nlp
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
      
      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
                - quantum-nlp
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_service_name

  alerting-rules.yml: |
    groups:
      - name: quantum-nlp-alerts
        rules:
          - alert: ServiceDown
            expr: up{job!="kubernetes-pods"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Service {{ $labels.job }} is down"
              description: "{{ $labels.job }} has been down for more than 1 minute"
          
          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High error rate detected"
              description: "Error rate is {{ $value }} for {{ $labels.job }}"
          
          - alert: HighLatency
            expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High latency detected"
              description: "95th percentile latency is {{ $value }}s for {{ $labels.job }}"
          
          - alert: QlafsSecurityIncident
            expr: qlafs_security_incidents_total > 0
            for: 0m
            labels:
              severity: critical
            annotations:
              summary: "QLAFS security incident detected"
              description: "{{ $value }} security incidents detected in QLAFS system"
          
          - alert: AgentVerificationFailed
            expr: rate(qlafs_verification_failures_total[5m]) > 0.05
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "Agent verification failures increasing"
              description: "Agent verification failure rate is {{ $value }} per second"