---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-portal
  namespace: quantum-nlp
  labels:
    app: web-portal
    component: frontend
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-portal
  template:
    metadata:
      labels:
        app: web-portal
        component: frontend
        tier: web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: web-portal
        image: ghcr.io/quantumlayerplatform-nlp/quantum-nlp-web-portal:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "http://nlp-gateway:8080"
        - name: NEXT_PUBLIC_WS_URL
          value: "ws://nlp-gateway:8080"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: web-portal
  namespace: quantum-nlp
  labels:
    app: web-portal
    component: frontend
spec:
  selector:
    app: web-portal
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-portal-ingress
  namespace: quantum-nlp
  labels:
    app: web-portal
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
  - host: web-portal.quantum-nlp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-portal
            port:
              number: 3000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-portal-hpa
  namespace: quantum-nlp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-portal
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80